import { ChangeDetectionStrategy, Component, WritableSignal, inject, signal } from '@angular/core';
import { GeminiService } from '../../services/gemini.service';
import { LoadingSpinnerComponent } from '../loading-spinner/loading-spinner.component';

interface PromptCategory {
  name: string;
  prompts: string[];
}

const CATEGORIZED_PROMPTS: PromptCategory[] = [
  {
    name: 'Artistic Movements',
    prompts: [
      'Render in the style of Impressionism, focusing on light and movement.',
      'Apply a Surrealist aesthetic, with dreamlike and bizarre imagery.',
      'Transform into a Cubist masterpiece, deconstructing subjects into geometric forms.',
      'Reimagine as a vibrant Pop Art piece with bold colors and halftone dots.',
      'Render in the classical, idealized style of the Renaissance.',
      'Give it a dramatic, high-contrast Baroque look with chiaroscuro lighting.',
      'Transform into a delicate, romantic Rococo painting.',
      'Recreate in the precise, machine-like style of Futurism.',
      'Adopt the minimalist, primary-colored approach of De Stijl (Mondrian).',
      'Apply a photorealistic style with meticulous detail.',
      'Transform into a Symbolist painting, rich with metaphorical meaning.',
      'Give it the clean, sharp lines of Precisionism.',
      'Render with the raw, untutored look of Art Brut.',
      'Adopt the decorative, patterned style of the Arts and Crafts movement.',
      'Reimagine as a Russian Constructivist propaganda poster.',
      'Apply the shimmering, mosaic-like quality of Pointillism.',
      'Transform into a grand, epic scene in the style of the Hudson River School.',
      'Render with the gritty realism of the Ashcan School.',
      'Adopt the flat perspectives and bold outlines of Japanese Ukiyo-e prints.',
      'Give it the look of a psychedelic poster from the 1960s.',
      'Transform into a piece of Op Art with dizzying optical illusions.',
      'Recreate as a conceptual art piece, where the idea is paramount.',
      'Apply a Dadaist collage style, combining disparate elements.',
      'Render in the gilded, decorative style of Gustav Klimt.',
      'Adopt the elongated, elegant figures of Mannerism.',
      'Transform into a Neoclassical painting with themes of heroism and order.',
      'Give it the soft, hazy look of Tonalism.',
      'Reimagine as a monumental, minimalist sculpture.',
      'Apply the vibrant, arbitrary colors of Fauvism.',
      'Render as an ancient Roman mosaic.',
      'Transform into a medieval illuminated manuscript page.',
      'Adopt the bold, graphic style of the Bauhaus school.',
      'Give it the look of an ethereal Pre-Raphaelite painting.',
      'Recreate as a graffiti mural in the style of Banksy.',
      'Apply the dreamy, symbolic visuals of Magical Realism.',
      'Transform into a video art still from the 1980s.',
      'Render with the layered, multi-perspective of Analytical Cubism.',
      'Adopt the bright, colorful style of Synthetic Cubism.',
      'Give it the look of a Victorian-era academic painting.',
      'Reimagine as a hard-edge painting with crisp boundaries between colors.',
      'Apply a color field painting style with large swaths of solid color.',
      'Transform into a kinetic art piece that implies motion.',
      'Render as a piece of feminist art, challenging traditional narratives.',
      'Adopt the aesthetic of a Situationist décollage.',
      'Give it the look of an Australian Aboriginal dot painting.',
      'Recreate as a folk art piece with a naive, charming quality.',
      'Apply the intricate, calligraphic style of Islamic art.',
      'Transform into a sublime, awe-inspiring Romantic landscape.',
    ],
  },
  {
    name: 'Cyberpunk & Sci-Fi',
    prompts: [
      'Infuse with a neon-noir, Blade Runner aesthetic.',
      'Transform into a high-tech, GITS-inspired cyborg.',
      'Render as a sprawling, dystopian cyberpunk cityscape.',
      'Apply a holographic glitch effect over the subject.',
      'Reimagine as a bio-mechanical creation by H.R. Giger.',
      'Give it a retro-futuristic look with vacuum tubes and chrome fins.',
      'Transform into a scene from a gritty, post-apocalyptic wasteland.',
      'Render as a sleek, minimalist interface from a sci-fi spaceship.',
      'Add augmented reality overlays and data streams.',
      'Depict as a character in a space opera with alien flora.',
      'Transform into a massive, derelict starship interior.',
      'Apply a "datamosh" glitch art style.',
      'Reimagine as a creature made of liquid metal.',
      'Render in the style of a vintage sci-fi pulp magazine cover.',
      'Give it a clean, utopian sci-fi aesthetic, like Star Trek.',
      'Transform into a scene within a vast virtual reality world.',
      'Add glowing data-tattoos and cybernetic implants.',
      'Recreate as a technical blueprint for a futuristic robot.',
      'Render as a soldier in powered armor.',
      'Depict a scene of first contact with an alien intelligence.',
      'Transform into a floating city in the clouds.',
      'Apply a dark, industrial sci-fi horror mood.',
      'Reimagine as a time-traveling vessel phasing through reality.',
      'Give it a vaporwave aesthetic with neon grids and Roman statues.',
      'Render as a rogue AI visualized in cyberspace.',
      'Transform into an alien landscape with bizarre geology.',
      'Add elements of a massive orbital space station.',
      'Recreate as a scene from a cosmic horror story.',
      'Depict a high-speed chase with flying vehicles.',
      'Transform into a genetically engineered creature.',
      'Apply the aesthetic of a retro 80s sci-fi anime.',
      'Reimagine as an artifact from an ancient alien civilization.',
      'Render as a bustling market on a distant planet.',
      'Give it a solarpunk theme, blending technology with nature.',
      'Transform into a giant mecha battle scene.',
      'Add a sense of awe with a Dyson sphere or ringworld.',
      'Recreate as a warning hologram from the future.',
      'Depict the inside of a wormhole or hyperspace tunnel.',
      'Render as a terraforming machine altering a planet.',
      'Transform into a character with psionic or telekinetic powers.',
      'Apply the look of a gritty, used-future, like in Alien or Star Wars.',
      'Reimagine as a sentient nebula in deep space.',
      'Give it the aesthetic of a classic raygun gothic illustration.',
      'Render as a mutant creature from a radioactive zone.',
      'Transform into an underwater research facility.',
      'Depict a scene of asteroid mining.',
      'Recreate as a clone emerging from a vat.',
      'Add elements of nanotechnology transforming the subject.',
      'Render as a utopian city with vertical gardens and clean energy.',
      'Transform into the command bridge of a generation ship.',
    ],
  },
  {
    name: 'Fantasy & Mythological',
    prompts: [
      'Illustrate as a character from a high-fantasy epic.',
      'Transform into a mythical creature from Greek mythology.',
      'Render as an enchanted, glowing forest scene.',
      'Depict as a powerful sorcerer casting a complex spell.',
      'Reimagine as an ancient, weathered dragon.',
      'Give it the style of a medieval illuminated manuscript.',
      'Transform into a scene from Norse mythology, like Ragnarok.',
      'Render as a majestic, elven city built into trees.',
      'Add ethereal fairy wings and a magical aura.',
      'Depict as a dwarven forge deep within a mountain.',
      'Recreate as a legendary cursed artifact.',
      'Illustrate in the dark, gothic fantasy style of Dark Souls.',
      'Transform into a celestial being made of starlight.',
      'Render as a whimsical scene from a fairy tale.',
      'Give it the look of a tarot card, rich with symbolism.',
      'Reimagine as a creature from Japanese folklore (yokai).',
      'Depict as a knight in ornate, magical armor.',
      'Transform into a lost, underwater city like Atlantis.',
      'Render as a creature from the Cthulhu Mythos.',
      'Add elements of alchemical symbols and diagrams.',
      'Illustrate as a dryad or nature spirit merging with a tree.',
      'Recreate as a grimoire page with arcane illustrations.',
      'Transform into a grand, floating castle in the sky.',
      'Depict as a guardian golem made of stone and vines.',
      'Render with the cute, charming style of a chibi fantasy character.',
      'Give it the epic, painted feel of a Magic: The Gathering card.',
      'Reimagine as a scene from the Egyptian Book of the Dead.',
      'Transform into a fearsome werewolf under a full moon.',
      'Illustrate as a stealthy rogue or assassin in the shadows.',
      'Depict as a serene, magical healing spring.',
      'Render as a powerful elemental (fire, water, earth, air).',
      'Give it the aesthetic of a Celtic myth, with intricate knots.',
      'Transform into a forgotten, cyclopean ruin in a jungle.',
      'Reimagine as a chaotic scene from the D&D Abyss.',
      'Illustrate as a wise, ancient treant.',
      'Depict a royal court in a high-fantasy kingdom.',
      'Render as a humble halfling village.',
      'Transform into a ghostly apparition haunting a graveyard.',
      'Give it the look of an artifact from Arthurian legend.',
      'Reimagine as a creature from Slavic folklore, like Baba Yaga.',
      'Illustrate as a powerful lich in its phylactery chamber.',
      'Depict a scene of a grand wizard\'s duel.',
      'Render as a majestic gryphon soaring through the mountains.',
      'Transform into a portal to another dimension.',
      'Give it the vibrant, colorful aesthetic of a Hindu deity.',
      'Reimagine as a vast, fantastical library of scrolls.',
      'Illustrate as a wandering monk with mystical powers.',
      'Depict a pact being made with a devil or archfiend.',
      'Render as a child-like, innocent fairy-folk creature.',
      'Transform into a legendary weapon, glowing with power.',
    ],
  },
  {
    name: 'Horror & Gothic',
    prompts: [
      'Apply a dark, gothic horror aesthetic.',
      'Render in the style of a Junji Ito manga, with body horror.',
      'Transform into a grotesque, Cronenberg-esque creature.',
      'Give it the look of a found footage horror film still.',
      'Reimagine as a creature from a silent horror movie like Nosferatu.',
      'Depict as a haunted, dilapidated Victorian mansion.',
      'Illustrate in the unsettling, surreal style of Zdzisław Beksiński.',
      'Add elements of cosmic horror, hinting at vast, unknowable evils.',
      'Transform into a creepy, porcelain doll.',
      'Render as a scene from a slasher film, with dramatic shadows.',
      'Give it the grainy, saturated look of a Giallo horror film.',
      'Reimagine as a ghostly figure in a long, dark hallway.',
      'Apply a filter of grime, decay, and urban rot.',
      'Illustrate as a page from a madman\'s diary.',
      'Transform into a monster from a John Carpenter film.',
      'Depict as a haunted forest with twisted, grasping trees.',
      'Render with a single, terrifying light source from below.',
      'Give it the aesthetic of a plague doctor in a deserted city.',
      'Reimagine as a zombie or other undead creature.',
      'Add unsettling text that looks like it was scratched into the image.',
      'Transform into a claustrophobic, labyrinthine space.',
      'Illustrate with the aesthetics of Southern Gothic.',
      'Depict as an abandoned, creepy carnival.',
      'Render as a specimen jar containing something horrible.',
      'Give it the look of an old, cursed photograph.',
      'Reimagine as a folk horror ritual in a remote village.',
      'Add a swarm of insects (spiders, locusts, etc.).',
      'Transform into a scene of demonic possession.',
      'Illustrate with a heavy, oppressive atmosphere of dread.',
      'Depict as a character with a terrifying, unnatural smile.',
      'Render as a submerged, aquatic horror scene.',
      'Give it the look of a glitching, haunted video game.',
      'Reimagine as a cryptic warning sign.',
      'Add shadowy figures just at the edge of perception.',
      'Transform into a skeletal or flayed figure.',
      'Illustrate as a scene viewed through a cracked peephole.',
      'Depict a room where something terrible has just happened.',
      'Render with the aesthetic of an analog horror video.',
      'Give it the look of a German Expressionist film, like Dr. Caligari.',
      'Reimagine as a religious horror icon.',
      'Add elements of medical horror, like old surgical tools.',
      'Transform into a scene from a Clive Barker story.',
      'Illustrate as a scary scarecrow in a desolate field.',
      'Depict the "monster\'s eye view" of a scene.',
      'Render as an unnervingly empty and silent location.',
      'Give it the look of a deep sea creature from the abyss.',
      'Reimagine as a figure made of writhing tentacles.',
      'Add a sense of being watched by something unseen.',
      'Transform into a vampire\'s crypt.',
      'Illustrate with a theme of uncanny valley.',
    ],
  },
  {
    name: 'Nature & Landscape',
    prompts: [
      'Reimagine as a majestic, Bob Ross-style landscape painting.',
      'Transform into a grand, Ansel Adams-inspired black and white photograph.',
      'Render as a vibrant, tropical rainforest teeming with life.',
      'Depict a serene, minimalist Japanese Zen garden.',
      'Illustrate as a dramatic, stormy seascape.',
      'Give it the look of a vast, arid desert at sunset.',
      'Transform into a scene of the Aurora Borealis over a frozen tundra.',
      'Render as a macro photograph of a flower, showing intricate details.',
      'Reimagine as a landscape viewed through a kaleidoscope.',
      'Depict an enchanted forest with bioluminescent plants.',
      'Give it the aesthetic of a vintage National Park poster.',
      'Transform into a single, ancient, wise-looking tree.',
      'Render as a powerful volcanic eruption.',
      'Illustrate as a peaceful countryside scene with rolling hills.',
      'Reimagine as a geological cross-section of the earth.',
      'Depict a terrarium or a miniature world in a bottle.',
      'Give it the look of an infrared photograph, with surreal colors.',
      'Transform into a majestic mountain range shrouded in mist.',
      'Render as a tranquil scene of a stream flowing through a forest.',
      'Illustrate as a field of wildflowers in a Ghibli-esque style.',
      'Reimagine as a landscape made entirely of candy and sweets.',
      'Depict a massive, awe-inspiring waterfall.',
      'Give it the look of a time-lapse photo showing the seasons change.',
      'Transform into a beautiful coral reef ecosystem.',
      'Render as a scene of a meteor shower in a clear night sky.',
      'Illustrate as a landscape painting by a Hudson River School artist.',
      'Reimagine as a desolate, beautiful salt flat.',
      'Depict a lush, hanging garden.',
      'Give it the look of a satellite image of a river delta.',
      'Transform into a deep, mysterious cave system with crystals.',
      'Render as a landscape on an alien planet.',
      'Illustrate as a bonsai tree, representing a whole landscape.',
      'Reimagine as a scene during a solar eclipse.',
      'Depict a grand canyon, carved by a river over millennia.',
      'Give it the look of a double exposure with an animal silhouette.',
      'Transform into a storm with dramatic lightning.',
      'Render as a peaceful scene of a misty morning lake.',
      'Illustrate as a patchwork of farm fields from above.',
      'Reimagine as a forest fire, with both destructive and regenerative themes.',
      'Depict a massive glacier or iceberg.',
      'Give it the aesthetic of a classic botanical illustration.',
      'Transform into a dense, humid mangrove swamp.',
      'Render as a scene of sand dunes in the wind.',
      'Illustrate as a natural rock arch or formation.',
      'Reimagine as the world on the back of a giant turtle.',
      'Depict the changing colors of autumn foliage.',
      'Give it the look of a landscape reflected in a water droplet.',
      'Transform into a field of giant mushrooms.',
      'Render as a powerful ocean wave, frozen in time.',
      'Illustrate as a terraced rice paddy field in Asia.',
    ],
  },
  {
    name: 'Abstract & Geometric',
    prompts: [
      'Deconstruct into a minimalist geometric composition.',
      'Transform into a swirling, chaotic fractal pattern.',
      'Render as a clean, precise vector illustration.',
      'Apply a liquid marbling or paper marbling effect.',
      'Reimagine as a complex, impossible Escher-like structure.',
      'Give it a low-poly, faceted look.',
      'Transform into a hypnotic, spiraling pattern.',
      'Render as a composition of overlapping, transparent shapes.',
      'Illustrate using only circles and ellipses.',
      'Deconstruct into a Bauhaus-inspired design with primary colors.',
      'Apply a glitchy, pixel-sorting effect.',
      'Reimagine as a string art creation.',
      'Give it the look of a generative art piece, created by code.',
      'Transform into an intricate, symmetrical mandala.',
      'Render as a topographic map with contour lines.',
      'Illustrate as a dynamic explosion of colorful particles.',
      'Deconstruct into a pattern of lines and grids, like a Sol LeWitt artwork.',
      'Apply a stained glass effect with bold black lines.',
      'Reimagine as a pattern of tessellating shapes.',
      'Give it the look of a complex, layered collage of textures.',
      'Transform into a single, continuous line drawing.',
      'Render as a visualization of sound waves or data.',
      'Illustrate using the Golden Ratio as a compositional guide.',
      'Deconstruct into a dynamic, Suprematist-style arrangement of shapes.',
      'Apply a moiré pattern effect.',
      'Reimagine as a 3D wireframe model.',
      'Give it the look of an abstract watercolor wash.',
      'Transform into a vibrant, patterned mosaic.',
      'Render as an arrangement of floating, isometric cubes.',
      'Illustrate as a minimalist composition focusing on negative space.',
      'Deconstruct into a rhythmic pattern of repeating elements.',
      'Apply an effect of shattered or broken pieces.',
      'Reimagine as a network diagram with nodes and connections.',
      'Give it the look of a risograph print with overlapping colors.',
      'Transform into a fluid, organic abstract shape.',
      'Render using only black and white with high contrast.',
      'Illustrate as a collection of calligraphic brush strokes.',
      'Deconstruct into a hard-edge painting with crisp color boundaries.',
      'Apply a diffusion-reaction (Turing) pattern.',
      'Reimagine as a color field painting with large, solid color areas.',
      'Give it the look of a microscopic or cellular pattern.',
      'Transform into a weaving or textile pattern.',
      'Render as a composition based on musical notation.',
      'Illustrate as a chaotic scribble or scrawl.',
      'Deconstruct into a minimalist composition with just a few key shapes.',
      'Apply a Voronoi diagram pattern.',
      'Reimagine as a light painting photograph.',
      'Give it the look of a delicate, intricate filigree pattern.',
      'Transform into a bold, graphic pattern inspired by African textiles.',
      'Render as an abstract sculpture of light and shadow.',
    ],
  },
  {
    name: 'Vintage & Retro',
    prompts: [
      'Give it the look of a faded, 1970s Kodachrome photograph.',
      'Transform into a bold, Art Deco travel poster from the 1920s.',
      'Render as a groovy, psychedelic piece of 1960s art.',
      'Apply the aesthetic of an 8-bit or 16-bit pixel art video game.',
      'Reimagine as a vintage, hand-drawn botanical illustration.',
      'Give it the grainy, black and white look of a film noir still.',
      'Transform into a mid-century modern illustration with clean lines.',
      'Render as a page from a 1950s science fiction comic book.',
      'Apply the look of a damaged, sepia-toned daguerreotype.',
      'Reimagine as a Victorian-era engraving.',
      'Give it the neon and chrome aesthetic of a 1980s album cover.',
      'Transform into a WWII-era propaganda poster.',
      'Render as a classic, airbrushed pin-up illustration.',
      'Apply the simple, charming style of a 1930s rubber hose cartoon.',
      'Reimagine as a design on a vintage tin toy.',
      'Give it the look of an old, water-stained map.',
      'Transform into a matchbook cover design from the 1940s.',
      'Render in the style of a technical illustration from an old encyclopedia.',
      'Apply the aesthetic of a 1990s Lisa Frank creation.',
      'Reimagine as a screen print concert poster from the 1970s.',
      'Give it the look of a silent film title card.',
      'Transform into a cross-stitch or embroidery piece.',
      'Render as a design on a vintage Pyrex dish.',
      'Apply the look of a faded, sun-bleached Polaroid photo.',
      'Reimagine as an Art Nouveau advertisement, perhaps for absinthe.',
      'Give it the aesthetic of an early, hand-colored photograph.',
      'Transform into a design for a 1960s airline travel bag.',
      'Render as a woodcut from the 15th century.',
      'Apply the look of a TV screen from the 1980s, complete with scan lines.',
      'Reimagine as a character from a Hanna-Barbera cartoon.',
      'Give it the aesthetic of a Soviet-era modernist poster.',
      'Transform into a page from a 1970s D&D player\'s handbook.',
      'Render as a cave painting from Lascaux.',
      'Apply the look of a faded mimeograph or risograph print.',
      'Reimagine as a design on a vintage bowling shirt.',
      'Give it the look of a Dutch Master\'s still life painting.',
      'Transform into a tramp art piece with notched wood.',
      'Render as a design for a vintage fruit crate label.',
      'Apply the look of an old, wrinkled and taped-up document.',
      'Reimagine as a character design by Max Fleischer.',
      'Give it the aesthetic of a 1990s GeoCities webpage.',
      'Transform into a rococo portrait with powdered wigs.',
      'Render as a scrimshaw carving on whale bone.',
      'Apply the look of a hand-painted magic lantern slide.',
      'Reimagine as a page from a pulp noir detective magazine.',
      'Give it the look of a cyanotype (blueprint) photograph.',
      'Transform into a Victorian silhouette portrait.',
      'Render as a design from the Memphis Group of the 1980s.',
      'Apply the look of a vintage railway travel poster.',
      'Reimagine as an alchemical diagram from the 17th century.',
    ],
  },
  {
    name: 'Cartoon & Anime',
    prompts: [
      'Illustrate in the whimsical, nostalgic style of Studio Ghibli.',
      'Transform into a dynamic, action-packed scene from a shonen anime.',
      'Render in the classic, rubber hose animation style of the 1930s.',
      'Adopt the clean, colorful aesthetic of a modern Cartoon Network show.',
      'Reimagine as a character in a dark, gritty 90s seinen anime.',
      'Give it the look of a Sunday morning newspaper comic strip.',
      'Transform into a vibrant, cel-shaded anime character.',
      'Render in the style of a beautiful, romantic shoujo manga panel.',
      'Adopt the thick-line, zany style of a 90s Nickelodeon cartoon.',
      'Reimagine as a detailed, mechanical design from a mecha anime.',
      'Give it the soft, pastel look of a slice-of-life anime.',
      'Transform into a grotesque, exaggerated caricature.',
      'Render in the bold, graphic style of a comic book cover.',
      'Adopt the flat, minimalist design of a UPA-era cartoon (Mr. Magoo).',
      'Reimagine as a frame from a rotoscoped animation.',
      'Give it the cute, super-deformed (chibi) art style.',
      'Transform into a panel from a European comic (bande dessinée).',
      'Render in the energetic, expressive style of an anime action sequence.',
      'Adopt the aesthetic of a Hanna-Barbera cartoon from the 60s.',
      'Reimagine as a frame from a lush, painterly Disney animated film.',
      'Give it the look of an underground comix (R. Crumb) illustration.',
      'Transform into a character from a magical girl anime.',
      'Render in the hyper-detailed, cyberpunk style of Akira.',
      'Adopt the simple, iconic style of Peanuts.',
      'Reimagine as a villain from a Saturday morning cartoon.',
      'Give it the look of a food scene from an anime, making it look delicious.',
      'Transform into a panel from a horror manga by Junji Ito.',
      'Render with the dynamic, forced perspective common in anime.',
      'Adopt the elegant, long-limbed style of a CLAMP manga.',
      'Reimagine as a background painting from a classic Looney Tunes short.',
      'Give it the look of a stop-motion animated character.',
      'Transform into a character with giant, expressive anime eyes.',
      'Render in the style of a political cartoon.',
      'Adopt the grainy, textured look of an old anime cel.',
      'Reimagine as a mascot character, like a Pokémon.',
      'Give it the look of a "CalArts" style modern cartoon.',
      'Transform into a dynamic manga page layout with speed lines.',
      'Render in the style of a beautifully illustrated children\'s book.',
      'Adopt the sketchy, fluid style of an animator\'s keyframes.',
      'Reimagine as a character from a sci-fi anime like Cowboy Bebop.',
      'Give it the look of a claymation character.',
      'Transform into a scene from an isekai anime.',
      'Render with the bold, high-contrast inks of a graphic novel.',
      'Adopt the surreal, inventive style of an independent animated short.',
      'Reimagine as a character with an over-the-top anime hairstyle.',
      'Give it the look of an animation background plate.',
      'Transform into a gag comic with a single punchline.',
      'Render in the style of a webtoon, with a long vertical scroll format.',
      'Adopt the cute, simple aesthetic of Sanrio characters.',
      'Reimagine as a character from an adventure-time style cartoon.',
    ],
  },
  {
    name: 'Photography Styles',
    prompts: [
      'Capture as a dramatic, high-contrast black and white photograph.',
      'Reimagine as a dreamy, soft-focus shot with a wide aperture.',
      'Apply the look of a long exposure, blurring motion and light.',
      'Render as a gritty, high-ISO street photography scene.',
      'Give it the look of a vintage, sepia-toned print.',
      'Transform into a macro photograph, revealing hidden details.',
      'Capture with a fisheye lens for a distorted, wide-angle view.',
      'Apply a tilt-shift effect, making it look like a miniature model.',
      'Render as a high-fashion editorial photograph.',
      'Give it the nostalgic, faded look of a Polaroid picture.',
      'Transform into a cyanotype (blueprint) image.',
      'Capture as a clean, minimalist product photograph on a white background.',
      'Apply a double exposure effect, merging two scenes into one.',
      'Render in the style of a candid, photojournalistic shot.',
      'Give it the aesthetic of a light leak or lens flare.',
      'Transform into a high-key photograph with bright tones and few shadows.',
      'Capture as a low-key photograph with dark tones and dramatic shadows.',
      'Apply the cross-processing (X-pro) effect for surreal colors.',
      'Render as a pinhole camera photograph with soft focus and vignetting.',
      'Give it the look of a wet plate collodion photograph.',
      'Transform into an anamorphic widescreen cinematic still.',
      'Capture with a shallow depth of field, isolating the subject.',
      'Apply a grainy, textured film look.',
      'Render as an aerial or drone photograph from directly above.',
      'Give it the vibrant, saturated colors of a Kodachrome slide.',
      'Transform into an infrared photograph with false colors.',
      'Capture as a silhouette against a bright background.',
      'Apply the look of a photo taken through a rainy window.',
      'Render as a time-slice photo, showing different times of day in one image.',
      'Give it the look of a disposable camera photo with a harsh flash.',
      'Transform into an abstract photograph focusing on texture and form.',
      'Capture with intentional camera motion for an abstract blur.',
      'Apply a bokeh effect with beautiful out-of-focus lights.',
      'Render as a high dynamic range (HDR) image with extreme detail.',
      'Give it the aesthetic of a Lomography photo with vignetting and saturated colors.',
      'Transform into a still from a 16mm film reel.',
      'Capture using the Brenizer method for a wide, panoramic portrait.',
      'Apply the look of a solarized (Sabattier effect) image.',
      'Render as a star trail photograph from a long night exposure.',
      'Give it the look of a photo with a cracked or broken lens.',
      'Transform into a photogram, made without a camera.',
      'Capture as a portrait with dramatic Rembrandt lighting.',
      'Apply a subtle color grading, like teal and orange.',
      'Render as a perfectly symmetrical photograph, Wes Anderson style.',
      'Give it the look of a photo taken on expired film.',
      'Transform into a paparazzi-style flash photograph.',
      'Capture from an extremely low angle, looking up.',
      'Apply the look of a stereoscopic (3D) image.',
      'Render as a composite photograph, blending multiple images seamlessly.',
      'Give it the look of a photo printed with a gum bichromate process.',
    ],
  },
  {
    name: 'Material & Texture',
    prompts: [
      'Recreate as a sculpture carved from polished marble.',
      'Transform into a rugged, weathered piece of driftwood.',
      'Render as if it were forged from rusted metal and copper.',
      'Illustrate as a delicate, intricate origami creation.',
      'Give it the texture of rough, hand-made paper.',
      'Reimagine as a stained glass window, glowing with light.',
      'Construct the scene entirely out of LEGO bricks.',
      'Transform into a soft, knitted or crocheted object.',
      'Render as a detailed, cross-hatched ink drawing.',
      'Apply the look of being carved from a single piece of jade.',
      'Reimagine as a vibrant, patterned mosaic tile artwork.',
      'Give it the texture of cracked, peeling paint on old wood.',
      'Transform into an object made of shimmering, iridescent crystal.',
      'Render as if it were made of flowing, molten gold.',
      'Illustrate as a chalk or pastel drawing on a rough surface.',
      'Recreate as a plush, felted wool sculpture.',
      'Give it the look of being etched into a sheet of glass.',
      'Transform into a claymation or plasticine model.',
      'Render as an intricate wire sculpture.',
      'Apply the texture of rich, embroidered velvet.',
      'Reimagine as a topographic map made of layered cardboard.',
      'Give it the look of being woven into a tapestry.',
      'Transform into a translucent object made of colored resin.',
      'Render as a piece of scrimshaw etched onto bone.',
      'Illustrate as a model made from circuit boards and electronic components.',
      'Recreate with the texture of shimmering fish scales.',
      'Give it the look of being made from pressed flowers and leaves.',
      'Transform into an ice sculpture, melting slightly.',
      'Render as a piece of intricate leather tooling.',
      'Apply the porous, organic texture of a sea sponge.',
      'Reimagine as a concrete brutalist structure.',
      'Give it the look of being made from iridescent mother-of-pearl.',
      'Transform into a glowing object made of neon tubes.',
      'Render as a paper quilling artwork.',
      'Illustrate as a woodblock print, showing the grain of the wood.',
      'Recreate with the texture of carbon fiber.',
      'Give it the look of a pearl with an opalescent sheen.',
      'Transform into an object made from recycled, found materials.',
      'Render as a polished, obsidian sculpture.',
      'Apply the texture of a fuzzy, flocked material.',
      'Reimagine as a balloon animal.',
      'Give it the look of being made from honeycomb and beeswax.',
      'Transform into a sculpture made of glowing plasma.',
      'Render as a piece of delicate porcelain with a crackle glaze.',
      'Illustrate with the texture of rough, uncut gemstones.',
      'Recreate as a sand sculpture on a beach.',
      'Give it the look of being made from feathers.',
      'Transform into an object made of swirling smoke.',
      'Render as a meticulously crafted miniature diorama.',
      'Apply the look of aged, verdigris-covered bronze.',
    ],
  },
  {
    name: 'Steampunk & Industrial',
    prompts: [
      'Incorporate intricate gears, cogs, and clockwork mechanisms.',
      'Reimagine as a steam-powered automaton.',
      'Add ornate brass and copper piping throughout the scene.',
      'Give it the aesthetic of a Victorian-era inventor\'s workshop.',
      'Transform into a massive, coal-powered steam engine.',
      'Render as a character wearing a top hat, goggles, and brass prosthetics.',
      'Illustrate as a grand, steam-powered airship or zeppelin.',
      'Add glowing vacuum tubes and complex analog dials.',
      'Reimagine as a detailed, mechanical blueprint on aged paper.',
      'Give it a gritty, industrial look with exposed rivets and welded seams.',
      'Transform into a scene from a bustling, soot-covered industrial city.',
      'Render as a clockwork animal or insect.',
      'Incorporate elements of a Jules Verne novel.',
      'Add polished wood paneling and velvet upholstery for a touch of luxury.',
      'Reimagine as a complex, Rube Goldberg-like machine.',
      'Give it the look of a handcrafted, artisanal piece of technology.',
      'Transform into a steam-powered vehicle, like a train or walker.',
      'Render as a portrait with a steampunk-inspired frame.',
      'Add ornate, filigree details to all mechanical parts.',
      'Reimagine as a map of a steampunk city, with pneumatic tube lines.',
      'Give it the feel of a world lit by gaslight and arc lamps.',
      'Transform into a weapon that is both elegant and mechanical.',
      'Render as a factory interior with massive, working machinery.',
      'Add a sense of wonder and adventure from the age of exploration.',
      'Reimagine as a steampunk version of a famous landmark.',
      'Give it the look of a device powered by a mysterious energy crystal.',
      'Transform into a scene from a steampunk-themed masquerade ball.',
      'Render as a complex navigational device, like an astrolabe.',
      'Add leather straps, belts, and pouches to the design.',
      'Reimagine as a prosthetic limb with exposed workings.',
      'Give it the aesthetic of a traveling caravan or mobile workshop.',
      'Transform into a massive, industrial blast furnace.',
      'Render as a scene with a steam-powered subway system.',
      'Add a sense of mystery with fog and steam obscuring the view.',
      'Reimagine as a character from a steampunk detective story.',
      'Give it the look of a device from the movie "Brazil".',
      'Transform into a musical instrument with pipes and gears.',
      'Render as an industrial landscape with smokestacks and warehouses.',
      'Add decorative pressure gauges and levers.',
      'Reimagine as a steampunk diving suit for exploring the abyss.',
      'Give it the aesthetic of a Tesla coil experiment.',
      'Transform into a library with mechanical book-retrieval systems.',
      'Render as a scene from a world where the Industrial Revolution took a different path.',
      'Add a monocle for an extra touch of class.',
      'Reimagine as a bridge made of iron, gears, and rivets.',
      'Give it the look of a vintage cash register, but more complex.',
      'Transform into a robot butler with a distinct personality.',
      'Render as an apothecary\'s shop with strange, bubbling concoctions.',
      'Add a layer of soot and grime to everything.',
      'Reimagine as a steampunk-inspired tarot card.',
    ],
  },
  {
    name: 'Minimalism',
    prompts: [
      'Reduce to a simple, single-line drawing.',
      'Transform into a composition of two or three bold, geometric shapes.',
      'Render using only a black and white color palette.',
      'Illustrate as a minimalist icon or logo.',
      'Focus on a single, isolated detail of the subject.',
      'Use negative space as the primary compositional element.',
      'Reimagine as a flat design vector illustration.',
      'Give it a clean, serene aesthetic inspired by Muji or Japanese design.',
      'Render with a limited, muted color palette of three colors.',
      'Abstract the subject into its most basic form.',
      'Illustrate as a simple silhouette against a plain background.',
      'Remove all texture, focusing only on shape and color.',
      'Reimagine as a haiku, visually represented.',
      'Give it the look of a minimalist architectural rendering.',
      'Render as a single, delicate brushstroke in the style of Zen calligraphy.',
      'Use only gradients of a single hue.',
      'Illustrate as a simple, elegant wireframe.',
      'Focus on the interplay of light and shadow on a simple form.',
      'Reimagine as a minimalist movie poster.',
      'Give it a clean, clinical, and sterile feel.',
      'Render as a composition balanced by a single, small point of color.',
      'Use typography as the main visual element.',
      'Illustrate as a perfectly centered, symmetrical object.',
      'Remove all background elements completely.',
      'Reimagine as a piece of furniture by Dieter Rams.',
      'Give it the look of a minimalist book cover.',
      'Render as a simple diagram or flowchart.',
      'Use a hard drop shadow to emphasize a simple shape.',
      'Illustrate with a single, continuous, unbroken line.',
      'Focus on the empty space within the composition.',
      'Reimagine as a simple, abstract logo for a tech company.',
      'Give it the aesthetic of a sand garden with raked lines.',
      'Render using only outlines, with no fill.',
      'Use a single, bold, flat color for the background.',
      'Illustrate as a piece of minimalist photography.',
      'Abstract the form until it is barely recognizable.',
      'Reimagine as a simple piece of sheet music.',
      'Give it the look of an ikebana (Japanese flower arrangement) with few elements.',
      'Render as a small object in a vast, empty space.',
      'Use subtle, nearly invisible textures.',
      'Illustrate with just a hint of a form, letting the viewer fill in the rest.',
      'Focus on a single, perfect geometric shape.',
      'Reimagine as a user interface with very few elements.',
      'Give it the clean, organized feel of a flat lay photograph.',
      'Render as a simple flag design.',
      'Use a gentle, monochromatic color scheme.',
      'Illustrate as a minimalist tattoo design.',
      'Focus on the absence of things.',
      'Reimagine as a simple, elegant piece of pottery.',
      'Give it the look of a single, perfect water droplet.',
    ],
  },
  {
    name: 'Food & Culinary Art',
    prompts: [
      'Reimagine as a hyperrealistic painting of a gourmet dish.',
      'Transform into a whimsical landscape made of food items.',
      'Render in the style of a beautifully illustrated recipe card.',
      'Give it the look of a food photograph from a high-end cooking magazine.',
      'Illustrate as a vibrant, colorful fruit tart.',
      'Deconstruct into its base ingredients, arranged in a neat flat lay.',
      'Reimagine as a character made of fruits and vegetables, like Arcimboldo.',
      'Give it the aesthetic of a rustic, farm-to-table meal.',
      'Transform into an elaborate, multi-tiered cake with fantasy decorations.',
      'Render as a diagram showing the flavor profile of a dish.',
      'Illustrate as a bento box, with neatly arranged components.',
      'Give it the look of a bubbling, magical potion or stew.',
      'Reimagine as a piece of molecular gastronomy, with foams and gels.',
      'Transform into a vintage advertisement for a food product.',
      'Render as a pattern on a piece of kitchen wallpaper.',
      'Illustrate as a messy, "after" picture of a delicious meal.',
      'Give it the warm, cozy feeling of fresh-baked bread.',
      'Reimagine as a dramatic "food porn" shot with dripping sauces.',
      'Transform into a candy or confectionary sculpture.',
      'Render as a minimalist dish served in a Michelin-starred restaurant.',
      'Illustrate as a page from a child\'s storybook about food.',
      'Give it the look of a bustling, chaotic kitchen during service.',
      'Reimagine as a pattern of colorful, sprinkled donuts.',
      'Transform into a simple, elegant sushi arrangement.',
      'Render as a deconstructed version of a classic cocktail.',
      'Illustrate as a cross-section of a complex dish, like a lasagna.',
      'Give it the aesthetic of a farmer\'s market stand.',
      'Reimagine as a still life painting of a feast, in the Dutch Golden Age style.',
      'Transform into an x-ray of a piece of food.',
      'Render as a beautiful, steaming cup of coffee with latte art.',
      'Illustrate as an ingredient in an apothecary\'s potion.',
      'Give it the look of food prepared for a Ghibli movie.',
      'Reimagine as a futuristic food pill that contains a whole meal.',
      'Transform into a geological strata made of cake layers.',
      'Render as a splash photograph of liquid.',
      'Illustrate as a character in a food-based video game.',
      'Give it the look of a medieval banquet.',
      'Reimagine as a scientific, botanical illustration of a food plant.',
      'Transform into a piece of food that is also a planet.',
      'Render as an abstract composition using spices and powders.',
      'Illustrate as a piece of food that is impossibly, magically glowing.',
      'Give it the look of a food truck menu.',
      'Reimagine as a scene from a competitive baking show.',
      'Transform into a charcuterie board with a vast array of items.',
      'Render as a macro shot of melting ice cream.',
      'Illustrate as a food item that is humorously out of place.',
      'Give it the look of a family recipe, handwritten and stained.',
      'Reimagine as a diagram of a complex sandwich build.',
      'Transform into a comforting, soulful bowl of ramen.',
      'Render as a pattern for a picnic blanket.',
    ],
  },
  {
    name: 'Architectural Styles',
    prompts: [
      'Reimagine as a Brutalist structure made of raw concrete.',
      'Transform into a whimsical, fantastical Gaudi-esque building.',
      'Render in the clean, minimalist style of Bauhaus architecture.',
      'Give it the ornate, soaring look of a Gothic cathedral.',
      'Illustrate as a sleek, futuristic skyscraper with impossible curves.',
      'Adopt the classical proportions and columns of Greco-Roman architecture.',
      'Reimagine as a cozy, organic Hobbit-hole integrated with nature.',
      'Give it the decorative, opulent style of a Baroque palace.',
      'Transform into a traditional Japanese pagoda with stacked eaves.',
      'Render as a Deconstructivist building that defies gravity and convention.',
      'Illustrate as a mid-century modern house with clean lines and glass walls.',
      'Adopt the intricate, geometric patterns of Islamic architecture.',
      'Reimagine as a fortified, medieval castle with towers and battlements.',
      'Give it the bold, glamorous aesthetic of Art Deco design.',
      'Transform into a sustainable, solarpunk building covered in plants.',
      'Render as a floor plan or blueprint of the structure.',
      'Illustrate as an ancient, ruined temple being reclaimed by the jungle.',
      'Adopt the half-timbered look of a Tudor-style house.',
      'Reimagine as a floating, tensegrity structure.',
      'Give it the look of a nomadic yurt or teepee.',
      'Transform into a monumental Egyptian pyramid or temple.',
      'Render as a cross-section, revealing the interior spaces.',
      'Illustrate as a colorful, playful Postmodern building.',
      'Adopt the log cabin aesthetic of frontier architecture.',
      'Reimagine as a building carved directly into a cliff face.',
      'Give it the look of a Russian Orthodox church with onion domes.',
      'Transform into a space station or lunar colony.',
      'Render as an isometric, pixel-art building from a video game.',
      'Illustrate as a treehouse village connected by rope bridges.',
      'Adopt the grand, imposing style of Neoclassical government buildings.',
      'Reimagine as an impossibly thin or tall structure.',
      'Give it the look of a charming, painted Venetian Gothic facade.',
      'Transform into a structure made of salvaged, repurposed materials.',
      'Render as an underground bunker or subterranean city.',
      'Illustrate as an ornate, Rococo interior.',
      'Adopt the adobe style of the American Southwest.',
      'Reimagine as a structure made of living, growing biological material.',
      'Give it the look of a Roman aqueduct or viaduct.',
      'Transform into a mobile, walking city like in Mortal Engines.',
      'Render as an architectural model made of wood or cardboard.',
      'Illustrate as a colonial-style building with a large veranda.',
      'Adopt the massive, stone-built style of the Inca Empire.',
      'Reimagine as a building that changes its shape.',
      'Give it the look of a lighthouse on a stormy coast.',
      'Transform into a panopticon or other disciplinary structure.',
      'Render as an abstract, conceptual architectural sketch.',
      'Illustrate as a Victorian "painted lady" house with gingerbread trim.',
      'Adopt the simple, functional style of a Shaker settlement.',
      'Reimagine as a research outpost in the Arctic.',
      'Give it the look of an ancient Mayan pyramid.',
    ],
  },
  {
    name: 'Cosmic & Space',
    prompts: [
      'Render as a swirling, colorful nebula.',
      'Transform into a detailed map of a constellation.',
      'Reimagine as a planet with strange, alien continents.',
      'Give it the look of a photo taken by the Hubble Space Telescope.',
      'Illustrate as a dramatic black hole, warping spacetime.',
      'Depict as a scene on the surface of Mars, with red dust and craters.',
      'Transform into a ringed planet like Saturn, but with different colors.',
      'Render as a cosmic entity or god.',
      'Illustrate as a spaceship exploring a new galaxy.',
      'Give it the look of a vintage astronomical chart.',
      'Reimagine as a fiery, explosive supernova.',
      'Depict a solar eclipse from the perspective of space.',
      'Transform into a dense, sparkling field of asteroids.',
      'Render as a human colony on the moon.',
      'Illustrate as the beautiful, shimmering tail of a comet.',
      'Give it the look of a wormhole or portal through space.',
      'Reimagine as a Dyson sphere enclosing a star.',
      'Depict a scene inside a generation ship traveling between stars.',
      'Transform into a celestial alignment of planets.',
      'Render as the glowing, ionized gas of an aurora on a gas giant.',
      'Illustrate as a futuristic space elevator.',
      'Give it the look of a gravitational lensing effect.',
      'Reimagine as a cosmic nursery where new stars are being born.',
      'Depict a first-contact scenario with an alien vessel.',
      'Transform into a view from the window of a space station.',
      'Render as a celestial body made entirely of crystal.',
      'Illustrate the Big Bang.',
      'Give it the look of a schematic for a warp drive engine.',
      'Reimagine as a creature that lives in the vacuum of space.',
      'Depict a satellite or space probe on a long, lonely journey.',
      'Transform into the Milky Way galaxy seen from the outside.',
      'Render as a terraforming process on a barren planet.',
      'Illustrate as a floating city within a nebula.',
      'Give it the look of a star chart from an ancient civilization.',
      'Reimagine as a planet with multiple moons in its sky.',
      'Depict the fiery re-entry of a spacecraft into the atmosphere.',
      'Transform into a map of dark matter in the universe.',
      'Render as a close-up of the surface of the sun.',
      'Illustrate the Oort cloud at the edge of the solar system.',
      'Give it the look of a retro rocket ship from the 1950s.',
      'Reimagine as a pulsar, emitting beams of radiation.',
      'Depict a scene of asteroid mining with robotic drones.',
      'Transform into the view from inside an astronaut\'s helmet.',
      'Render as a visualization of different cosmic background radiation.',
      'Illustrate a galactic collision.',
      'Give it the look of an orrery, a mechanical model of the solar system.',
      'Reimagine as a planet that is actually a giant, living organism.',
      'Depict a ringworld structure around a star.',
      'Transform into a beautiful, abstract representation of a physics theory.',
      'Render as the final, red giant phase of a star.',
    ],
  },
  {
    name: 'Glitch & Digital Art',
    prompts: [
      'Apply a heavy datamoshing effect, blending and tearing pixels.',
      'Transform into an ASCII art representation.',
      'Render with a pixel sorting glitch, creating vertical or horizontal streaks.',
      'Give it the look of a corrupted JPEG file with blocky artifacts.',
      'Illustrate as a piece of vaporwave art with pinks, cyans, and checkerboards.',
      'Apply a CRT screen effect, with scan lines and phosphor glow.',
      'Reimagine as a 3D anaglyph (red/blue) image.',
      'Give it the aesthetic of a glitched-out VHS tape.',
      'Transform into a piece of generative art created with code.',
      'Render with a chromatic aberration effect, separating color channels.',
      'Illustrate as a low-poly 3D model with flat shading.',
      'Apply a dithering effect, like on an old computer screen.',
      'Reimagine as a hypnotic, looping GIF.',
      'Give it the look of a terminal or command-line interface.',
      'Transform into a collection of windows and dialog boxes from a 90s OS.',
      'Render with a "world scan" effect, as if a scanner is passing over it.',
      'Illustrate using only the 16 colors of a classic computer palette.',
      'Apply a digital mosaic or pixelation effect.',
      'Reimagine as a QR code that contains a hidden message.',
      'Give it the look of a fractured or shattered screen.',
      'Transform into a piece of net art from the early internet.',
      'Render with exaggerated digital noise and compression artifacts.',
      'Illustrate as a 3D wireframe mesh.',
      'Apply a feedback loop effect, like pointing a camera at its own screen.',
      'Reimagine as a digital spectrograph or waveform visualization.',
      'Give it the look of a buffer underrun or screen tearing in a video game.',
      'Transform into a piece of plotter art, made with mechanical arms.',
      'Render with a lens distortion or barrel distortion effect.',
      'Illustrate as a point cloud, a collection of 3D data points.',
      'Apply an "in-painting" effect where parts are digitally removed.',
      'Reimagine as a piece of demoscene art.',
      'Give it the look of a faulty LCD screen with dead pixels.',
      'Transform into a psychedelic, deep-dream visualization.',
      'Render with a slit-scan photography effect, distorting time and space.',
      'Illustrate as a texture map for a 3D object.',
      'Apply a bit-shifting or data corruption effect to the image data.',
      'Reimagine as a piece of interactive art that responds to a cursor.',
      'Give it the look of a vector graphic with visible Bézier curves.',
      'Transform into a "normal map" used for 3D lighting.',
      'Render as a procedurally generated landscape.',
      'Illustrate with a bloom or light bleed effect around bright areas.',
      'Apply a posterization effect, reducing the number of colors.',
      'Reimagine as a piece of art made with Microsoft Paint.',
      'Give it the look of a computer overheating and artifacting.',
      'Transform into a glitchy, looping cinemagraph.',
      'Render as a fractal flame algorithm visualization.',
      'Illustrate as a shader effect from a video game.',
      'Apply an edge detection filter, highlighting outlines.',
      'Reimagine as a piece of ANSI art from old bulletin board systems.',
      'Give it the look of a digital watermark or overlay.',
    ],
  },
  // Add 10+ more categories here
];


@Component({
  selector: 'app-image-remix',
  templateUrl: './image-remix.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LoadingSpinnerComponent],
})
export class ImageRemixComponent {
  private readonly geminiService = inject(GeminiService);

  prompt = signal<string>('Make the colors more vibrant and surreal.');
  isLoading = signal<boolean>(false);
  loadingStep = signal<string>('');
  result = signal<string | null>(null);
  error = signal<string | null>(null);
  
  contentImage = signal<{ base64: string; mimeType: string; name: string } | null>(null);
  styleImage = signal<{ base64: string; mimeType: string; name: string } | null>(null);
  
  promptCategories: PromptCategory[] = CATEGORIZED_PROMPTS;
  showPromptSuggestions = signal<boolean>(false);
  activeCategory = signal<PromptCategory>(this.promptCategories[0]);

  async applyStyleTransfer(): Promise<void> {
    if (!this.contentImage() || !this.styleImage()) {
      this.error.set('Please upload both a content and a style image.');
      return;
    }

    this.isLoading.set(true);
    this.result.set(null);
    this.error.set(null);

    try {
      // Step 1: Analyze images and prompt to create a new generation prompt
      this.loadingStep.set('Step 1/2: Analyzing images...');
      const newImagePrompt = await this.geminiService.generatePromptForStyleTransfer(
        this.prompt(),
        this.contentImage()!,
        this.styleImage()!
      );

      // Step 2: Generate the new image using the prompt from step 1
      this.loadingStep.set('Step 2/2: Applying new style...');
      // Using 1:1 aspect ratio as we can't infer it from the upload. A more advanced version could detect this.
      // FIX: The `generateImage` service method expects 3 arguments (prompt, aspectRatio, numberOfImages).
      const imageUrls = await this.geminiService.generateImage(newImagePrompt, '1:1', 1);
      
      // FIX: The `generateImage` service method returns an array of strings. Set the first result.
      this.result.set(imageUrls[0]);

    } catch (e: unknown) {
      this.error.set(e instanceof Error ? e.message : 'An unknown error occurred during the style transfer process.');
    } finally {
      this.isLoading.set(false);
      this.loadingStep.set('');
    }
  }
  
  onContentFileChange(event: Event): void {
    this.handleFileChange(event, this.contentImage);
  }

  onStyleFileChange(event: Event): void {
    this.handleFileChange(event, this.styleImage);
  }

  private handleFileChange(event: Event, imageSignal: WritableSignal<{ base64: string; mimeType: string; name: string; } | null>): void {
     const input = event.target as HTMLInputElement;
    if (input.files && input.files[0]) {
      const file = input.files[0];
      const reader = new FileReader();
      reader.onload = (e) => {
        const dataUrl = e.target?.result as string;
        const base64 = dataUrl.split(',')[1];
        imageSignal.set({ base64, mimeType: file.type, name: file.name });
        this.error.set(null);
      };
      reader.readAsDataURL(file);
    }
    // Clear the input value so the same file can be selected again
    input.value = '';
  }
  
  updatePrompt(event: Event): void {
    const input = event.target as HTMLInputElement;
    this.prompt.set(input.value);
  }
  
  triggerFileInput(fileInput: HTMLInputElement): void {
    fileInput.click();
  }

  togglePromptSuggestions(): void {
    this.showPromptSuggestions.update(value => !value);
  }

  selectSuggestedPrompt(selectedPrompt: string): void {
    this.prompt.set(selectedPrompt);
    this.showPromptSuggestions.set(false);
  }

  selectCategory(category: PromptCategory): void {
    this.activeCategory.set(category);
  }
}
